#just do not try to run, not even nearly done
try:
    os.remove('/sd/Encoder.csv')
try:
    os.remove('/sd/Steering_Wheel.csv')
try:
    os.remove('/sd/Dashboard.csv')
try:
    os.remove('/sd/BMS_Cell_V_1_4.csv')
try:
    os.remove('/sd/BMS_Cell_V_5_8.csv')
try:
    os.remove('/sd/BMS_Cell_V_9_12.csv')
try:
    os.remove('/sd/BMS_Cell_Temp.csv')
try:
    os.remove('/sd/BMS_Volt_Current.csv')
try:
    os.remove('/sd/BMS_State.csv')
try:
    os.remove('/sd/BMS_Error_Flags.csv')
try:
    os.remove('/sd/Motor_1_Status.csv')
try:
    os.remove('/sd/Motor_2_Status.csv')
try:
    os.remove('/sd/Front_Lights_Status.csv')
try:
    os.remove('/sd/Rear_Lights_Status.csv')
try:
    os.remove('/sd/ERROR.txt')
